DROP DATABASE IF EXISTS CoronaTestDB;
CREATE DATABASE IF NOT EXISTS CoronaTestDB;
USE CoronaTestDB;


CREATE TABLE IF NOT EXISTS USER (
    USERID         INTEGER NOT NULL,
    VORNAME        VARCHAR(50),
    NACHNAME       VARCHAR(50),
PRIMARY KEY (USERID)
);

CREATE TABLE IF NOT EXISTS RESULTS (
    RESULTID       INTEGER NOT NULL,
    RESULTNAME     VARCHAR(50),
PRIMARY KEY (RESULTID)
);

CREATE TABLE IF NOT EXISTS TESTS (
    USERID         INTEGER NOT NULL,
    DATUM          DATE,
    RESULTID         INTEGER NOT NULL,
FOREIGN KEY (USERID)  REFERENCES USER (USERID),
FOREIGN KEY (RESULTID)  REFERENCES RESULTS (RESULTID)
);

USE CoronaTestDB;

INSERT INTO RESULTS (RESULTID, RESULTNAME) VALUES ('1', 'Negaiv');
INSERT INTO RESULTS (RESULTID, RESULTNAME) VALUES ('2', 'Positiv');



COMMIT WORK;